### ISSUE TITLE
Lautstärkesteuerung in %

### ISSUE THREAD

**Issue by ipod86** [iobroker-community-adapters/ioBroker.sony-bravia#107]
Hallo, 

das letzte Adapterupdate nutzt wie es aussieht eine andere Möglichkeit die Daten vom TV zu bekommen. 

Bisher gibt es ja die Möglichkeit, über die Buttons "volume up" und "down" die Lautstärke anzupassen. 

Es wäre jedoch klasse, die Lautstärke auch in % angeben zu können. Noch besser, wenn der Wert im ioBroker auch aktualisiert wird, wenn man es über den TV steuert (die Werte also immer synchron sind, wie bei powerStatusActive).

**Comment by ThomasBra** [comment]
Ich habe einmal versucht das wie gefordert umzusetzen. Mit meinem Gerät funktioniert es leider nicht wie vorgesehen. Ich habe es lt. Schnittstellenbeschreibung umgesetzt.
https://pro-bravia.sony.net/develop/integrate/rest-api/spec/service/audio/v1_2/setAudioVolume/index.html

In meinem Fall verändert sich die Lautstärke immer nur um einen Zähler, egal ob relative oder absolute Werte geschickt werden.

Hier https://github.com/ThomasBra/ioBroker.sony-bravia

**Comment by ipod86** [comment]
Werde es testen sobald verfügbar.
Kann ich die Version per git laden?

Würde die Variante auch die Lautstärke im ioBroker anpassen wenn ich sie über die Fernbedienung ändere?

**Comment by ipod86** [comment]
Hab grad über git installiert.
Bekomme im ioBroker V 1.0. 5 angezeigt.

Finde aber keinen Datenpunkt für die Lautstärke.

**Comment by ThomasBra** [comment]
Ich habe bei mir eine Soundbar verbunden, dass könnte die Quelle meines Problems sein.

**Comment by ipod86** [comment]
Hast du ein target angegeben?
Ohne wird ja angeblich alles angepasst.

**Comment by ThomasBra** [comment]
Ja, das Target wird mit angegeben. Es wird aber auch mit Soudbar das Target Speaker ("target": "speaker") erwartet.

Ich werde da noch etwas nachforschen.
