### ISSUE TITLE
TV Programme und Apps als Werteliste 

### ISSUE THREAD

**Issue by ipod86** [iobroker-community-adapters/ioBroker.sony-bravia#108]
Hallo,

in der neuen Adapterversion gibt es ja Datenpunkte um direkt auf Sender oder Apps starten zu können.

Es wäre klasse, wenn jeweils noch eine Werteliste (heißt das so?) angelegt wird.

Also alle Sender bzw Apps je in einem Datenpunkt geschrieben werden um zB ein Dropdown in seiner Visualisierung anzulegen.

**Comment by ThomasBra** [comment]
Ich habe noch nicht viele Adapter geschrieben würde mich aber gerne weiter daran versuchen.

Was ist eine solche Werteliste und wie muss es aufgebaut sein?

Hast du ggf. ein Beispiel an dem ich mir das ansehen kann, z.B. ein anderer Adapter oder ein Objektdaten?

**Comment by ipod86** [comment]
So sieht der Datenpunkt aus.
Anstatt 1:one kann man auch eins:eins schreiben. Mit der Nummer hat den Vorteil, dass man die Kanal immer eingeben könnte.

`{
  "_id": "0_userdata.0.Werteliste",
  "type": "state",
  "common": {
    "name": "Werteliste",
    "role": "",
    "type": "number",
    "read": true,
    "write": true,
    "desc": "Manuell erzeugt",
    "min": 0,
    "max": 5,
    "def": 0,
    "states": "0:zero;1:one;2:two;3:three;4:four;5:five",
    "custom": {
      "lovelace.0": {
        "enabled": true,
        "entity": "input_select",
        "name": "Werteliste"
      }
    }
  },
  "native": {},
  "from": "system.adapter.admin.0",
  "user": "system.user.admin",
  "ts": 1625727167627,
  "acl": {
    "object": 1636,
    "state": 1636,
    "owner": "system.user.admin",
    "ownerGroup": "system.group.administrator"
  }
}`

**Comment by ipod86** [comment]
Nachtrag:

So sieht ein Datenpunkt aus dem Shelly Adapter aus:

`{
  "type": "state",
  "common": {
    "name": "Input Type",
    "type": "string",
    "role": "state",
    "read": true,
    "write": true,
    "states": {
      "button": "button",
      "switch": "switch"
    }
  },
  "native": {},
  "from": "system.adapter.shelly.0",
  "user": "system.user.admin",
  "ts": 1645123061683,
  "_id": "shelly.0.shellyplus1#a8032abccc2c#1.Input0.InputType",
  "acl": {
    "object": 1636,
    "state": 1636,
    "owner": "system.user.admin",
    "ownerGroup": "system.group.administrator"
  }
}`

**Comment by ThomasBra** [comment]
Ich arbeite im Moment an einem ersten Versuch für die Wertelisten. Für AV Inhalte sollte es schon funktionieren.

Bitte prüfe doch einmal, ob es so ist wie du es dir vorgestellt hast.

Hier https://github.com/ThomasBra/ioBroker.sony-bravia

**Comment by ipod86** [comment]
Die Liste klappt wunderbar.
Lässt sich auch in die Visu einbauen.

Was jetzt natürlich mega klasse wäre, wenn sich der Datenpunkt noch automatisch auf den aktuellen Sender stellt, wenn man auf der Fernbedienung umschaltet.

Hab gesehen, dass. Ei anderen Sachen auch eine Liste erstellt wird. Klasse.

**Comment by ipod86** [comment]
![Screenshot_20220317-234547_Fully Kiosk Browser](https://user-images.githubusercontent.com/66136363/158906495-5b78cc6a-ba77-4bb2-a144-dd37c74b761c.jpg)

**Comment by ThomasBra** [comment]
Das mit dem aktuell halten der Datenpunkte ist noch ein Todo.

Ich erweitere das bei Gelegenheit.

**Comment by ipod86** [comment]
Cool, 
sonst hätte ich es mir mit einem blockly gebaut.
So warte ich noch.

Eigentlich hätte der Adapter jetzt eine höhere Versionsnummer verdient. 
Von 1.x auf 2.x.

Vor deinen Updates war er ja doch recht simpel. Jetzt weiß ich, dass ich nur noch Sony-TVs bekomme 🤣
