### ISSUE TITLE
Nach Update V1.0.5 Fehlermeldungen und seltsames Verhalten

### ISSUE THREAD

**Issue by MMeinhardt1** [iobroker-community-adapters/ioBroker.sony-bravia#110]
Hallo,

seit dem gestrigen Update auf 1.0.5 bekomme ich die untenstehenden Fehlermeldungen.
Ich habe zwei Instanzen installiert, eine für einen 65XD7505 die ohne Fehler läuft und die zweite für einen 55W805B bei der die Fehlermeldungen erscheinen wenn dieser ausgeschaltet ist. Der 55er ist nur per WLAN ins Netzwerk eingebunden, vielleicht spielt es ein Rolle, der 65er ist per LAN eingebunden.

```
sony-bravia.0 | 2022-03-02 17:57:08.978 | error | contentInfo cannot be determined Error: getPlayingContentInfo. Response error, status code: 404.
sony-bravia.0 | 2022-03-02 17:57:08.975 | error | powerStatus cannot be determined Error: getPowerStatus. Response error, status code: 404.
sony-bravia.0 | 2022-03-02 17:56:58.966 | error | contentInfo cannot be determined Error: getPlayingContentInfo. Response error, status code: 404.
sony-bravia.0 | 2022-03-02 17:56:58.962 | error | powerStatus cannot be determined Error: getPowerStatus. Response error, status code: 404.
sony-bravia.0 | 2022-03-02 17:56:48.956 | error | contentInfo cannot be determined Error: getPlayingContentInfo. Response error, status code: 404.
sony-bravia.0 | 2022-03-02 17:56:48.954 | error | powerStatus cannot be determined Error: getPowerStatus. Response error, status code: 404.
sony-bravia.0 | 2022-03-02 17:56:38.975 | error | contentInfo cannot be determined Error: getPlayingContentInfo. Response error, status code: 404.
sony-bravia.0 | 2022-03-02 17:56:38.971 | error | powerStatus cannot be determined Error: getPowerStatus. Response error, status code: 404.
sony-bravia.0 | 2022-03-02 17:11:58.811 | error | contentInfo cannot be determined Error: getPlayingContentInfo. Response error, status code: 404.
sony-bravia.0 | 2022-03-02 17:11:58.808 | error | powerStatus cannot be determined Error: getPowerStatus. Response error, status code: 404.
sony-bravia.0 | 2022-03-02 17:11:48.808 | error | contentInfo cannot be determined Error: getPlayingContentInfo. Response error, status code: 404.
sony-bravia.0 | 2022-03-02 17:11:48.806 | error | powerStatus cannot be determined Error: getPowerStatus. Response error, status code: 404.
sony-bravia.0 | 2022-03-02 17:11:38.820 | error | contentInfo cannot be determined Error: getPlayingContentInfo. Response error, status code: 404.
sony-bravia.0 | 2022-03-02 17:11:38.816 | error | powerStatus cannot be determined Error: getPowerStatus. Response error, status code: 404.
sony-bravia.0 | 2022-03-02 17:11:28.818 | error | contentInfo cannot be determined Error: getPlayingContentInfo. Response error, status code: 404.
sony-bravia.0 | 2022-03-02 17:11:28.815 | error | powerStatus cannot be determined Error: getPowerStatus. Response error, status code: 404.
sony-bravia.0 | 2022-03-02 16:24:03.636 | error | contentInfo cannot be determined Error: ESOCKETTIMEDOUT
sony-bravia.0 | 2022-03-02 16:24:03.635 | error | powerStatus cannot be determined Error: ESOCKETTIMEDOUT
sony-bravia.0 | 2022-03-02 16:23:53.649 | error | contentInfo cannot be determined Error: ESOCKETTIMEDOUT
sony-bravia.0 | 2022-03-02 16:23:53.626 | error | powerStatus cannot be determined Error: ESOCKETTIMEDOUT
sony-bravia.1 | 2022-03-02 10:36:24.198 | error | contentInfo cannot be determined Error: ETIMEDOUT
sony-bravia.1 | 2022-03-02 10:36:24.196 | error | powerStatus cannot be determined Error: ETIMEDOUT
sony-bravia.1 | 2022-03-02 10:28:37.548 | error | contentInfo cannot be determined Error: connect ECONNREFUSED 192.168.178.32:80
sony-bravia.1 | 2022-03-02 10:28:37.546 | error | powerStatus cannot be determined Error: connect ECONNREFUSED 192.168.178.32:80
sony-bravia.1 | 2022-03-02 02:57:38.002 | error | contentInfo cannot be determined Error: connect ECONNREFUSED 192.168.178.32:80
sony-bravia.1 | 2022-03-02 02:57:37.976 | error | powerStatus cannot be determined Error: connect ECONNREFUSED 192.168.178.32:80
```

Wenn weitere Infos oder Logs benötigt werden, dann bitte Bescheid geben.

EDIT: Die DPs "Power on" (sony-bravia.0.function.AAAAAQAAAAEAAAAuAw==) und "Power off" (sony-bravia.0.function.AAAAAQAAAAEAAAAvAw==) funktionieren nicht mehr so wie vorher, ist da etwas geändert worden oder sind diese jetzt an anderer Stelle zu finden? Es scheint so als schalten sie sowohl bei "true" und "false" in Wechsel je nach Zustand des Gerätes. Bin da etwas verwirrt.

Vielen Dank

**Comment by duczz** [comment]
@ThomasBra Looks like some Problems in your new version, you are the only one who work in this Adapter, maybe you can fix some issue here?

**Comment by ThomasBra** [comment]
Im Bereich des SendIRCC ("Power on" sowie "Power off") habe ich versucht keine Änderungen zu machen. Soweit ich den Code verstehe sollte hier aber nur beim Wechsel auf den Status true reagiert werden.

Die "cannot be determined" Errors sind unerwartet, da vorher die Existenz des Geräts geprüft wird und nur nach Bestätigung die Zustände abgefragt.

Ich habe das Fehlerhandling überarbeitet und entschärft.

**Comment by MMeinhardt1** [comment]
Hi, 
ich habe gerade ein Update durchlaufen lassen und nun bekomme ich die folgenden Meldungen von meinem 55W805B. 

2022-03-17 20:23:11.366  - error: sony-bravia.1 (23938) Error: connect EHOSTUNREACH 192.168.178.32:80
2022-03-17 20:23:11.369  - error: sony-bravia.1 (23938) SchemeList Error: connect EHOSTUNREACH 192.168.178.32:80
2022-03-17 20:23:11.372  - error: sony-bravia.1 (23938) ApplicationList Error: connect EHOSTUNREACH 192.168.178.32:80

**Comment by ThomasBra** [comment]
Kann es sein das die Fehler direkt beim Starten des Adapters auftreten, wenn der 55W805B ausgeschaltet ist (nicht im WLAN)?

Ich denk mir mal was aus das diese Fehler nicht auftreten, bzw. die API Initialisierung solange verzögert wird bis das Gerät erreichbar ist.

**Comment by MMeinhardt1** [comment]
Hi, ich werde es testen und den Adapter mal neustarten wenn der Fernseher läuft. 
Heute Nacht kamen noch diese Fehler,

2022-03-18 02:57:24.611 - error: sony-bravia.1 (29134) powerStatus cannot be determined Error: connect ECONNREFUSED 192.168.178.32:80
2022-03-18 02:57:24.645 - error: sony-bravia.1 (29134) contentInfo cannot be determined Error: connect ECONNREFUSED 192.168.178.32:80
