### ISSUE TITLE
Error: "ContentList Error" and adapter stays yellow in instance overview

### ISSUE THREAD

**Issue by vansen** [iobroker-community-adapters/ioBroker.sony-bravia#116]
**Describe the bug**  
I am experiencing an issue where the adapter is unable to fully connect to the tv. The log shows the following errors:
TV is a Sony Bravia: KD-65X8507C.
I am not sure if the latest upgrade caused the error. I also tried downgrading also to v. 1.0.1 (I think it was), the error disappeared, but instance stays yellow as well.
The strange thing is that the tv can be controlled though, but I am unable to identify if it connected and powered on, this information just stays false.

Hope someone is able to help me with this,

Thank you

**Screenshots & Logfiles**  
Screenshot of error log:
![image](https://user-images.githubusercontent.com/13270526/161395858-2bf54735-7431-48e7-bf70-df4649571af2.png)

![image](https://user-images.githubusercontent.com/13270526/161395998-6d3e2e64-7221-4f6b-9dcb-e5e159acc96e.png)

**Versions:**  
 - Adapter version: 1.0.5
 - JS-Controller version: 4.0.21
 - Node version: 14.19.1
 - Operating system: ubuntu

**Comment by ThomasBra** [comment]
Same Issue as #109

We are challenged to find a solution.

**Comment by vansen** [comment]
I think I have found the issue. It is related to the ping execution permissions with linux. "bin/ping" seems block and needs "s" permission. This line did the trick for me: `sudo chmod u+s /bin/ping`. Adapter now turned green again.

**Comment by DrHappy90** [comment]
> I think I have found the issue. It is related to the ping execution permissions with linux. "bin/ping" seems block and needs "s" permission. This line did the trick for me: `sudo chmod u+s /bin/ping`. Adapter now turned green again.

you made it. It works perfect.

**Comment by Apollon77** [comment]
and "iob fix" was not doing the job too?
