### ISSUE TITLE
TypeError: Cannot read property 'then' of undefined

### ISSUE THREAD

**Issue by holofury** [iobroker-community-adapters/ioBroker.sony-bravia#118]
Hallo,

seit einem der letzten Updates auf aktuell 1.0.8 taucht folgende Meldung bei mir im Log auf:

sony-bravia.0 | 2022-04-30 10:14:06.994 | error | TypeError: Cannot read property 'then' of undefined 

Was kann man dagegen tun?

**Comment by holofury** [comment]
?

**Comment by ingod68** [comment]
here too



sony-bravia.0 | 2022-06-05 12:51:38.542 | error | TypeError: Cannot read property 'then' of undefined

**Comment by holofury** [comment]
Wird der Adapter noch gepflegt?
Keine Reaktion seit 7 Wochen :-(

**Comment by justr1** [comment]
Am 25.04.22 hat Ingo unter anderem im Modul iobroker/node-modules/iobroker.sony-bravia/lib/bravia.js die beiden Zeilen:
```
131: send(code);
141: send(ircc.value);
```
geändert in:
```
131: send(code).then(resolve, reject);
141: send(ircc.value).then(resolve, reject);
```
Als Workaround lässt sich das leicht rückgängig machen und der Adapter neu starten.

@Apollon77 : Kannst du dir das bitte anschauen und korrigieren? Keine Ahnung, wie das korrekt sein muss.

Vielen Dank und viele Grüße
justr

**Comment by Apollon77** [comment]
Ahhhh ... wtf who writes such code ... defining  a method in a method with the same name *gmpfff* ...

Can someone please install GitHub version (attention: with npm 6 an GitHub install can tage 10+minutes ... just wait). Then I can release this fix. Thank you @justr1 for the ultimate tip

**Comment by justr1** [comment]
Hab jetzt bestimmt 2 oder 3 Stunden gewartet und nichts ist passiert. ;) Glaube aber der aktuelle Admin-Adapter hat ein prinzipielles Problem. Musste gestern auch schon per Terminal Adapter-Updates einspielen, da beim Admin einfach nichts passiert ist. Hab da aber schon nach vielleicht 2 Minuten aufgegeben. Mit
`$ iobroker url iobroker-community-adapters/ioBroker.sony-bravia --host Juergens-Mini13.fritz.box`
im Terminal musste ich jetzt auch nur 5 Minuten warten.

Der Fehler ist weg und der Adapter scheint soweit zu funktionieren.

Vielen Dank und viele Grüße
justr1

(Hab bei der Initialisierung des Adapters seit ca. einem halben Jahr noch ein paar Fehler "ContentList Error: getContentList ...", aber das ist eine andere Geschichte. Mache ich ein eigenes Issue. Tritt auch nur beim Adapter-Start auf und stört eigentlich nicht.)

**Comment by Apollon77** [comment]
Ja, eine Admin Version 6.1.x war buggy wegen updates, die aktuellste Beta Adin hat das wieder gefixt! Und ja bitte anderesd issue s... dann kommt das ggf noch mit rein!

**Comment by Apollon77** [comment]
fixed sicne 1.0.9
