### ISSUE TITLE
TypeError: Cannot read property 'then' of undefined

### ISSUE THREAD

**Issue by duczz** [iobroker-community-adapters/ioBroker.sony-bravia#129]
@Apollon77 Hey Ingo,

könntest du den Fehler ggf korrigieren? Der knallt mir seit kurzem das ganze log zu

![image](https://user-images.githubusercontent.com/25475385/173754164-73a13dd3-5f19-4b8f-b14e-9307430f5a4c.png)

**Comment by Apollon77** [comment]
duplicate #118
