### ISSUE TITLE
Please release v1.0.3

### ISSUE THREAD

**Issue by raintonr** [iobroker-community-adapters/ioBroker.sony-bravia#32]
I notice the last version of the code is 1.0.2 but NPM only shows 1.0.1. Please release the later version. Thx :)

**Comment by duczz** [comment]
@DutchmanNL Ja, bitte freigeben, läuft einwandfrei

**Comment by raintonr** [comment]
@Apollon77 ... you asked to be mentioned as a reminder :)

**Comment by Apollon77** [comment]
Please reinstall from github as 1.0.3 ... i did some dependency updates and such  ... would release that then after you say that it is ok

**Comment by raintonr** [comment]
> Please reinstall from github as 1.0.3 ... i did some dependency updates and such ... would release that then after you say that it is ok

Yes, working fine here, thx.

**Comment by Apollon77** [comment]
npm release done. will come to latest 2am

**Comment by raintonr** [comment]
![image](https://user-images.githubusercontent.com/3794098/100643034-d97e0800-3339-11eb-8558-0ef91c134f57.png)

I'm on the stable repo but v1.0.3 isn't showing as available even though I see it in NPM. Do authors have to manually bump versions in the ioBroker repo files?

**Comment by Apollon77** [comment]
Yes, stable is done automatically after latest was "proofed working", so we normally wait some days and check installation number (so the dev of the adapter). alternative after 14 days there is a remonder issue which gets created. you can use the details for the adapter on www.iobroker.net to see installation number sof a certain version. 1.0.3 is installed by 67 users, which is 5,5% of all installs in the meantime. this is a good start
