### ISSUE TITLE
PowerOn, TvPower nicht

### ISSUE THREAD

**Issue by galegro** [iobroker-community-adapters/ioBroker.sony-bravia#67]
We're using a BRAVIA-KDL-50W805B. The options VolumeUp, VolumeDown, Mute, PowerOff work properly, but TvPower, Power on didn't work.☹

Testing: I've used the corresponding datapoints in iobroker objects on MacBook and iPad.

Adapter version is 1.0.3

**Comment by MMeinhardt1** [comment]
I have the same problem with the KDL-55W805B 😞

**Comment by MMeinhardt1** [comment]
With the „nettools“ Adapter in iobroker you can use the wake on lan function to switch on the TV.
