### ISSUE TITLE
PowerOff crasht Instanz

### ISSUE THREAD

**Issue by duczz** [iobroker-community-adapters/ioBroker.sony-bravia#70]
Wenn man PowerOff betätigt Crasht der Adapter
Version 1.0.3

`
<html>
<body>

sony-bravia.0 | 2021-05-05 17:52:26.062 | debug | (28595) System command: /bin/ping -n -w 2 -c 1 192.168.178.38
-- | -- | -- | --
sony-bravia.0 | 2021-05-05 17:52:16.050 | debug | (28595) System command: /bin/ping -n -w 2 -c 1 192.168.178.38
sony-bravia.0 | 2021-05-05 17:52:16.016 | info | (28595) starting. Version 1.0.3 in /opt/iobroker/node_modules/iobroker.sony-bravia, node: v12.21.0, js-controller: 3.2.16
sony-bravia.0 | 2021-05-05 17:51:44.740 | debug | (28479) system.adapter.admin.0: logging true
sony-bravia.0 | 2021-05-05 17:51:44.573 | warn | (28479) Terminated (UNCAUGHT_EXCEPTION): Without reason
sony-bravia.0 | 2021-05-05 17:51:44.573 | info | (28479) terminating
sony-bravia.0 | 2021-05-05 17:51:44.067 | error | (28479) Exception-Code: EHOSTUNREACH: connect EHOSTUNREACH 192.168.178.38:80
sony-bravia.0 | 2021-05-05 17:51:44.067 | error | at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1144:16)
sony-bravia.0 | 2021-05-05 17:51:44.067 | error | (28479) Error: connect EHOSTUNREACH 192.168.178.38:80
sony-bravia.0 | 2021-05-05 17:51:44.067 | error | (28479) unhandled promise rejection: connect EHOSTUNREACH 192.168.178.38:80
sony-bravia.0 | 2021-05-05 17:51:44.066 | error | (28479) Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().
sony-bravia.0 | 2021-05-05 17:51:42.128 | debug | (28479) system.adapter.admin.0: logging false
sony-bravia.0 | 2021-05-05 17:51:37.934 | debug | (28479) System command: /bin/ping -n -w 2 -c 1 192.168.178.38
sony-bravia.0 | 2021-05-05 17:51:27.924 | debug | (28479) System command: /bin/ping -n -w 2 -c 1 192.168.178.38
sony-bravia.0 | 2021-05-05 17:51:27.910 | info | (28479) starting. Version 1.0.3 in /opt/iobroker/node_modules/iobroker.sony-bravia, node: v12.21.0, js-controller: 3.2.16
sony-bravia.0 | 2021-05-05 17:51:27.268 | debug | (28479) statesDB connected
sony-bravia.0 | 2021-05-05 17:51:27.267 | debug | (28479) States connected to redis: 127.0.0.1:9000
sony-bravia.0 | 2021-05-05 17:51:27.262 | debug | (28479) States create User PubSub Client
sony-bravia.0 | 2021-05-05 17:51:27.262 | debug | (28479) States create System PubSub Client
sony-bravia.0 | 2021-05-05 17:51:27.258 | debug | (28479) Redis States: Use Redis connection: 127.0.0.1:9000
sony-bravia.0 | 2021-05-05 17:51:27.257 | debug | (28479) objectDB connected
sony-bravia.0 | 2021-05-05 17:51:27.254 | debug | (28479) Objects connected to redis: 127.0.0.1:9001
sony-bravia.0 | 2021-05-05 17:51:27.241 | debug | (28479) Objects client initialize lua scripts
sony-bravia.0 | 2021-05-05 17:51:27.241 | debug | (28479) Objects create User PubSub Client
sony-bravia.0 | 2021-05-05 17:51:27.240 | debug | (28479) Objects create System PubSub Client
sony-bravia.0 | 2021-05-05 17:51:27.239 | debug | (28479) Objects client ready ... initialize now
sony-bravia.0 | 2021-05-05 17:51:27.215 | debug | (28479) Redis Objects: Use Redis connection: 127.0.0.1:9001
sony-bravia.0 | 2021-05-05 17:51:24.279 | info | (27957) Terminated (ADAPTER_REQUESTED_TERMINATION): Without reason
sony-bravia.0 | 2021-05-05 17:51:24.278 | info | (27957) terminating
sony-bravia.0 | 2021-05-05 17:51:23.777 | info | (27957) Got terminate signal TERMINATE_YOURSELF
sony-bravia.0 | 2021-05-05 17:49:44.923 | info | (27957) starting. Version 1.0.3 in /opt/iobroker/node_modules/iobroker.sony-bravia, node: v12.21.0, js-controller: 3.2.16
sony-bravia.0 | 2021-05-05 17:49:13.477 | warn | (6034) Terminated (UNCAUGHT_EXCEPTION): Without reason
sony-bravia.0 | 2021-05-05 17:49:13.477 | info | (6034) terminating
sony-bravia.0 | 2021-05-05 17:49:12.966 | error | (6034) Exception-Code: EHOSTUNREACH: connect EHOSTUNREACH 192.168.178.38:80
sony-bravia.0 | 2021-05-05 17:49:12.966 | error | at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1144:16)
sony-bravia.0 | 2021-05-05 17:49:12.966 | error | (6034) Error: connect EHOSTUNREACH 192.168.178.38:80
sony-bravia.0 | 2021-05-05 17:49:12.966 | error | (6034) unhandled promise rejection: connect EHOSTUNREACH 192.168.178.38:80
sony-bravia.0 | 2021-05-05 17:49:12.963 | error | (6034) Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().

</body>
</html>`

**Comment by SirFlour** [comment]
habe den gleichen Fehler / Verhalten. Konntest du es beheben?

**Comment by duczz** [comment]
@ldittmar81 schaut es sich bei Zeiten an sagte er im Forum, lassen wir ihm mal noch Zeit :)
