### ISSUE TITLE
Sony-KE-48A9 not supported?

### ISSUE THREAD

**Issue by UweLoyal** [iobroker-community-adapters/ioBroker.sony-bravia#91]
Adapter does not work with Sony-KE-48A9, only sony-bravia.0.info.powerStatusActive is shown correct.
Is my Sony-KE-48A9 not supported by the adapter?

Rgds
Uwe Loyal

**Comment by ThomasBra** [comment]
Is Simple IP Control enabled?

https://pro-bravia.sony.net/develop/integrate/ssip/overview/index.html

**Comment by UweLoyal** [comment]
Yes!
Made some own JavaScrits, which works fine.
Used Sony developer Document as Info.

Mit freundlichen Grüßen

Uwe Loyal
Am 12. Dez. 2021, 21:41 +0100 schrieb Thomas Braune ***@***.***>:
