### ISSUE TITLE
More device informations

### ISSUE THREAD

**Issue by ThomasBra** [iobroker-community-adapters/ioBroker.sony-bravia#92]
Device state informations by the sony rest api https://pro-bravia.sony.net/develop/integrate/rest-api/spec/index.html

getPlayingContentInfo
{
    "result": [{
        "source": "extInput:hdmi",
        "title": "HDMI 2",
        "uri": "extInput:hdmi?port=2"
    }],
    "id": 103
}

getInterfaceInformation
{
    "result": [{
        "modelName": "FW-55BZ35F",
        "serverName": "",
        "interfaceVersion": "5.0.1",
        "productName": "BRAVIA",
        "productCategory": "tv"
    }],
    "id": 33
}

**Comment by duczz** [comment]
@ThomasBra Thanks for your features, i have some errors on getcontentlist, can you check it?

![image](https://user-images.githubusercontent.com/25475385/152671212-e03d2606-945f-4cf3-8134-5dfb4a3806a3.png)

**Comment by ThomasBra** [comment]
<html>
<body>


14 | Unsupported Version | “error”: [14, “Unsupported Version”] | For cases when the requested version is not supported on the specified service.
-- | -- | -- | --



</body>
</html>

Your Bravia TV does not support version 1.5 requests. As a result, the information on AV Contents and TV Channels cannot be loaded. Which Bravia TV are you using? The model information should appear under "info.modelInformation".

**Comment by duczz** [comment]
KDL-50W829B BRAVIA/2.5.0

**Comment by ThomasBra** [comment]
The methode "getSchemeList" don't pull the full channel URI.

getSchemeList v1.0
{
    "result": [[
        {"scheme": "extInput"},
        {"scheme": "fav"}
    ]],
    "id": 1
}

getSourceList v1.0
{
    "result": [[
        {"source": "extInput:hdmi"},
        {"source": "extInput:component"},
        {"source": "extInput:cec"},
        {"source": "extInput:widi"}
    ]],
    "id": 1
}

getContentList v1.5
{
    "result": [[
        {
            "uri": "extInput:hdmi?port=1",
            "title": "HDMI 1",
            "index": 0
        },
        {
            "uri": "extInput:hdmi?port=2",
            "title": "HDMI 2",
            "index": 1
        },
        {
            "uri": "extInput:hdmi?port=3",
            "title": "HDMI 3/ARC",
            "index": 2
        },
        {
            "uri": "extInput:hdmi?port=4",
            "title": "HDMI 4",
            "index": 3
        }
    ]],
    "id": 88
}

I need the methode "getContentList" for the full URI.

Would a firmware update be conceivable? I tested at interface version 5.4.0. I can no longer find the documentation for version 2.5.0.
https://www.sony.de/electronics/support/lcd-tvs-kdlxxw8xxb-series/kdl-50w829b/downloads/00017151

**Comment by duczz** [comment]
I have this Firmware already, but not working.
is it possible to check the firmware version and use than the right api version? 
I think the getSchemeList was is the last release of this

**Comment by ThomasBra** [comment]
I will include the method getSupportedApiInfo to check the versions in advance. Unfortunately I can't test this on myself.

What kind of messages occur regularly? Maybe I can check this better. Thanks for the feedback

**Comment by duczz** [comment]
Perfect thanks

This messages comes every 10-20 Seconds when my tv is off
![image](https://user-images.githubusercontent.com/25475385/152958012-f29a4d28-24b1-46d2-a89a-f341189e78a7.png)

**Comment by ThomasBra** [comment]
I've made some improvements. My TV is still working, your problems are probably fixed. Can you test it before I release the branch?

https://github.com/ThomasBra/ioBroker.sony-bravia

**Comment by ThomasBra** [comment]
That is interesting. 

The error code means that the requested method does not exist.
<html>
<body>


12 | No Such Method | “error”: [12, “No Such Method”] | For cases when the requested API does not exist.
-- | -- | -- | --



</body>
</html>
What confuses me is that this method already exists in version 1.0 of the REST interface. https://pro-bravia.sony.net/develop/integrate/rest-api/spec/service/guide/v1_0/getSupportedApiInfo/index.html

If there were no REST interface, we wouldn't get any answers either.

**I have improve the error handling, but unfortunately I cannot provide the intended function for your version.**

**Comment by duczz** [comment]
okay, thanks

![image](https://user-images.githubusercontent.com/25475385/153742889-e269f808-aaeb-457c-84a0-926f8b914cf3.png)

**Comment by ThomasBra** [comment]
Sorry @duczz for the bad method handling. The new update should now work again.

**Comment by duczz** [comment]
Perfekt, all problems are fixed, only the api problem dont works why my tv is maybe to old.
Can you push it to the original fork?

**Comment by ThomasBra** [comment]
fork iss pushed
