### ISSUE TITLE
Strange Objects without Values with Sony KD-55A8

### ISSUE THREAD

**Issue by cdaerr** [iobroker-community-adapters/ioBroker.sony-bravia#99]
**Describe the bug**  
The adapter delivers only one working Object (connection). The Object powerStatusActive does not deilver any values. The other objects don't have meaninful names and have no values.

**To Reproduce**  
1. Install Adapter
2. Connect TV following the instructions
3. Look at Objects

**Screenshot**  
![grafik](https://user-images.githubusercontent.com/98185044/151934064-81bf0d2b-171b-4ed7-96d0-3e77efd6cfb7.png)

Export of Object strucutre:
[sony-bravia.0.json.zip](https://github.com/iobroker-community-adapters/ioBroker.sony-bravia/files/7977017/sony-bravia.0.json.zip)

**Expected behavior**  
Adapter provides Meaningful names and status values or provides an error message if not possible.

**Versions:**  
 - Adapter version: 1.0.3
 - JS-Controller version: 3.3.22
 - Node version: v14.18.3
 - Operating system: ubuntu server

**Comment by cdaerr** [comment]
Yes bug is already reproducable.

**Comment by cdaerr** [comment]
Yes bug is still reproducable.

**Comment by cdaerr** [comment]
Yes bug is still reproducable.

**Comment by Apollon77** [comment]
TW: "the cryptic states" are buttons that can trigger actions ... so they will never have  a meaningful value.

please add new debug log with 1.0.9

**Comment by cdaerr** [comment]
Hi,

thanks, here is the debug log:
![grafik](https://user-images.githubusercontent.com/98185044/187525566-77a1ae00-7d16-4111-8ba7-4c379ae17233.png)

TV was an and it replys to ping:
![grafik](https://user-images.githubusercontent.com/98185044/187525732-918fcc01-7950-4433-9de5-946b0a80e4a6.png)

**Comment by Apollon77** [comment]
EAI_AGAIN means that the dns lookup is not possible somehow. what dfoes the ping from CLI of the obroker host say?

**Comment by cdaerr** [comment]
What do you mean with CLI?

**Comment by cdaerr** [comment]
If I use the IP Address directly, the log shows like this:
![image](https://user-images.githubusercontent.com/98185044/187605050-f6e8318d-60ff-4ad6-82e8-560f5cd94cf1.png)

**Comment by Apollon77** [comment]
CLI = Command Line Interface ... aka an der "Shell"

Ok jetzt ists aber ein anderer Fehler ECONNREFUSED heisst das die Netzwerkverbindung vom Gert abgelehnt wurde - heisst JETZT kann er die IP auflösen ... aber dort nichts erreichen

**Comment by cdaerr** [comment]
Ja, er kann den Namen anscheinend nur auflösen, wenn ich die Domain anhänge, obwohl der Server die gleiche hat. Aber das ist ein anderes Problem und hat nichts mit ioBroker oder dem Adapter zu tun.

Jetzt ist nur die Frage, warum er keine Verbindung mit dem TV bekommt?

**Comment by Apollon77** [comment]
Da kich so ein Gerät nciht habe und daher auch nur basis-Support machen kann weiss ich das nicht ... vllt mal im Forum nachfragen?
